### ISSUE TITLE
only what is about data to try your code?

### ISSUE THREAD

**Issue by Sandy4321** [xuetf/KDD_CUP_2020_Debiasing_Rush#2]
Great code !
Thanks for sharing
only what is about data to try your code?

is this data good to use
https://www.kaggle.com/hxshine/kdd-2020

or I need another data link?

**Comment by xuetf** [comment]
> Great code !
> Thanks for sharing
> only what is about data to try your code?
> 
> is this data good to use
> https://www.kaggle.com/hxshine/kdd-2020
> 
> or I need another data link?

Hello, I have uploaded the data to the baidu pan, https://pan.baidu.com/s/1P2h7APGUEscdnGlYQpgh-g (password: kilm),  can you open this link?

**Comment by Sandy4321** [comment]
still problem
can you just upload to another shearing service
maybe https://www.dropbox.com/?landing=dbv2
or google drive 
or
https://wrzucplik.pl/upload.html   file transfer till 5 GB
or...

![image](https://user-images.githubusercontent.com/11426119/85475926-fb05e700-b584-11ea-9c01-f0c3735b8e9f.png)

**Comment by xuetf** [comment]
> still problem
> can you just upload to another shearing service
> maybe https://www.dropbox.com/?landing=dbv2
> or google drive
> or
> https://wrzucplik.pl/upload.html file transfer till 5 GB
> or...
> 
> ![image](https://user-images.githubusercontent.com/11426119/85475926-fb05e700-b584-11ea-9c01-f0c3735b8e9f.png)

you can download data by google drive, 
https://drive.google.com/file/d/1meJrZY3xFZHfuOJI5VSaTy9zVbQgLore/view?usp=sharing

**Comment by Sandy4321** [comment]
great thanks
